### ISSUE TITLE
TODO: Documentation problems and additions

### ISSUE THREAD

**Issue by mawosoft** [mawosoft/BenchmarkDotNetToolbox#11]
- [ ] Add xrefService for MS docs to docfx.json
- [ ] Add xrefs for BenchmarkDotNet
- [ ] Fix *View Source* links to repo
- [ ] Update placeholder pages
- [ ] Add conceptual and sample docs

**Comment by mawosoft** [comment]
In order to fix xrefs for BenchmarkDotNet I had to download an older version of  xrefmap.yml from the gh-pahes branch and also add `baseUrl: https://benchmarkdotnet.org/` to make it work.

See mawosoft/BenchmarkDotNet#7

**Comment by mawosoft** [comment]
> * [ ]  With xrefs fixed, some xrefs are shortened too much: `DefaultColumnProviders.Params`, `DefaultColumnProviders.Jobs`
Sadly there is no easy fix.
- DocFX ignores text inside `<see></see>` tag. Intellisense shows it correctly (and doesn't have the shortening problem in the first place).
```C#
/// <see cref="DefaultColumnProviders.Params">DefaultColumnProviders.Params</see>
```
- DocFX shows MD xref tag correctly, but Intellisense doesn't recognize it and shows the tag as plain text.
```C#
/// [DefaultColumnProviders.Params](xref.BenchmarkDotNet.Columns.DefaultColumnProviders.Params)
```
- Only workaround seems to be to use a overwrite file.
