### ISSUE TITLE
TODO: Docs formatting (DocFX templates)

### ISSUE THREAD

**Issue by mawosoft** [mawosoft/BenchmarkDotNetToolbox#16]
For Docs content see #11

- [ ] Add logo and favicon
- [ ] ToC, header links, and affix aren't visible if Javascript is disabled. **WONTFIX**
- [ ] Change code wrapping (breaks in the middle of words)
- [ ] Change parameter table wrapping (dito)
This is actually a problem everywhere (headers, ToC, etc)
