### ISSUE TITLE
TODO: BenchmarkRunInfos

### ISSUE THREAD

**Issue by mawosoft** [mawosoft/BenchmarkDotNetToolbox#7]
- [x] Rename 'Replacement' to Override? _**Yes.**_
- [x] Only use a single override job? _**Yes.**_
Seems logical if we're only looking at InProcess.
But if user wants to debug out-of-process and just reduce the runtime via DryJob multiple jobs for multiple frameworks would make sense. _**Maybe.**_ OTOH, he could just switch the target of the host. The host project has to support all the frameworks anyway.
- [x] Give public access to PostProcessor via separate method. _**via `Add()` and `AddRange()`.**_
Use case: WhatifFilter -> IEnumerable<BenchmarkRunInfo> -> apply override
- [x] Do we need to implement IDispose? _**No.**_ See #9 
- [x] Should we return Items as IReadOnlyList? _**Yes.**_
- [x] Verify that the underlying Dispose implementation is safe for our purposes. _**OK.**_ See #9 and mawosoft/BenchmarkDotNet#6
Postprocessor can simply discard unused original `BenchmarkCase`(s) and reuse their existing `ParameterInstances` because changing a job or even the number of jobs will still have each param/method combo at least once.
